# Generated by Django 3.2.8 on 2021-10-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211023_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('name', models.CharField(blank=True, help_text='name', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('first_name', models.CharField(blank=True, help_text='first name', max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, help_text='last name', max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='email address', max_length=254, unique=True),
        ),
    ]
