# Generated by Django 3.2.8 on 2021-10-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211024_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='name',
        ),
    ]
