# Generated by Django 3.2.8 on 2021-10-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_restaurantprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='username', max_length=160, null=True, unique=True),
        ),
    ]
