# Generated by Django 3.2.9 on 2021-11-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20211104_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='capacity',
            new_name='number_of_seats',
        ),
        migrations.AddField(
            model_name='table',
            name='is_outside',
            field=models.BooleanField(default=False, help_text='Is table outside'),
        ),
    ]
