# Generated by Django 3.2.9 on 2021-12-08 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20211104_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lower_date',
        ),
    ]
